name: Node.js CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      MONGO_URL: ${{ secrets.MONGO_URL }}
      PORT: ${{ secrets.PORT }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20.10.0'

      - name: Install dependencies
        run: npm install

      - name: create .env file
        run: |
          echo "MONGO_URL=${{ secrets.MONGO_URL }}" > .env
          echo "PORT=${{ secrets.PORT }}" >> .env

      - name: Run Jest tests
        run: |
          npm test       

      - name: Build Docker image
        run: |
          docker build -t mkmukulkumar/user-management-api:latest .

      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Push Docker image
        run: |
          docker push mkmukulkumar/user-management-api:latest
